name: Unit tests

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  run_tests:
    strategy:
      matrix:
        include:
          - python_version: "3.10"
          - python_version: "3.12"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: pip
      - name: install test tools
        run: pip install tox
      - name: run unittests
        run: tox -e py3
